-- Add columns for photo 2, 3, 4 (photo/photo_blob/photo_s3_url are index 0)
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_2 VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_2_blob BYTEA;
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_2_s3_url VARCHAR(500);

ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_3 VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_3_blob BYTEA;
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_3_s3_url VARCHAR(500);

ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_4 VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_4_blob BYTEA;
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_4_s3_url VARCHAR(500);
