-- Run this only if users.id is an IDENTITY column and Accept does not update id.
-- If you get: "column \"id\" of relation \"users\" is not an identity column"
-- then your id column is already updatable (e.g. SERIAL). You do NOT need this script.
-- In that case, try Accept again and check the Next.js server terminal for [Accept] logs.

-- ALTER TABLE users ALTER COLUMN id SET GENERATED BY DEFAULT;
