-- Revert profile_id: use the main id column only. Run this so "Accept" can change id to 5000+.
-- 1) Drop profile_id column and index
ALTER TABLE users DROP COLUMN IF EXISTS profile_id;
DROP INDEX IF EXISTS idx_users_profile_id;

-- 2) Allow updating users.id (required when admin accepts and id is set to 5000+)
--    If id is GENERATED ALWAYS AS IDENTITY, PostgreSQL blocks UPDATE; switch to BY DEFAULT.
DO $$
BEGIN
  IF (SELECT a.attidentity FROM pg_catalog.pg_attribute a
      JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
      WHERE c.relname = 'users' AND a.attname = 'id' AND a.attnum > 0 AND NOT a.attisdropped) = 'a' THEN
    ALTER TABLE users ALTER COLUMN id SET GENERATED BY DEFAULT;
  END IF;
EXCEPTION WHEN OTHERS THEN
  NULL;  -- Column may not be identity (e.g. SERIAL); ignore
END $$;

-- 3) Notifications: add ON UPDATE CASCADE so when users.id changes (e.g. on accept), references stay valid
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_user_id_fkey;
ALTER TABLE notifications
  ADD CONSTRAINT notifications_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
