// Raasi options (zodiac order: Aries to Pisces)
// Provided list from user (without emoji)
export const raasiOptions = [
  'Mesha (Aries) – మేషం',
  'Vrishabha (Taurus) – వృషభం',
  'Mithuna (Gemini) – మిథునం',
  'Karka (Cancer) – కర్కాటకం',
  'Simha (Leo) – సింహం',
  'Kanya (Virgo) – కన్య',
  'Tula (Libra) – తుల',
  'Vrischika (Scorpio) – వృశ్చికం',
  'Dhanu (Sagittarius) – ధనుస్సు',
  'Makara (Capricorn) – మకరం',
  'Kumbha (Aquarius) – కుంభం',
  'Meena (Pisces) – మీనం'
];

// Star options (Nakshatra order)
export const starOptions = [
  'Ashwini – అశ్విని',
  'Bharani – భరణి',
  'Krittika – కృత్తిక',
  'Rohini – రోహిణి',
  'Mrigashira – మృగశిర',
  'Ardra – ఆర్ద్ర',
  'Punarvasu – పునర్వసు',
  'Pushya – పుష్య',
  'Ashlesha – ఆశ్లేష',
  'Magha – మఘ',
  'Purva Phalguni – పూర్వ ఫల్గుణి',
  'Uttara Phalguni – ఉత్తర ఫల్గుణి',
  'Hasta – హస్త',
  'Chitra – చిత్ర',
  'Swati – స్వాతి',
  'Vishakha – విశాఖ',
  'Anuradha – అనురాధ',
  'Jyeshtha – జ్యేష్ఠ',
  'Moola – మూల',
  'Purva Ashadha – పూర్వాషాఢ',
  'Uttara Ashadha – ఉత్తరాషాఢ',
  'Shravana – శ్రవణ',
  'Dhanishta – ధనిష్ఠ',
  'Shatabhisha – శతభిష',
  'Purva Bhadrapada – పూర్వ భాద్రపద',
  'Uttara Bhadrapada – ఉత్తర భాద్రపద',
  'Revati – రేవతి'
];

export const padamOptions = [
  '1st Padam',
  '2nd Padam',
  '3rd Padam',
  '4th Padam'
];

// Gothram options - used for both Gothram and Uncle Gothram
// Full list provided by user
export const gothramOptions = [
  'Aagyamula',
  'Abhimanyakula',
  'Acharyakula',
  'Adhvarakula',
  'Agasthyakula',
  'Agnikula',
  'Ahalyakula',
  'Ainakula',
  'Akrurakula',
  'Amalakula',
  'Anantakula',
  'Anapakula',
  'Anayakula',
  'Andhikula',
  'Anthakula',
  'Anumarshanakula',
  'Anupalakula',
  'Anushistakula',
  'Arakamulakula',
  'Arasakula',
  'Atreyakula',
  'Ayanakula',
  'Badishista',
  'Balishista',
  'Bhallavakula',
  'Bharadwajasa',
  'Bheemashista',
  'Bhomagosheelakula',
  'Bramarakula',
  'Bramhakula',
  'Brihaspatikula',
  'Budarakula',
  'Budhakula',
  'Budhikula',
  'Chanashistakula',
  'Chandakula',
  'Chandanakula',
  'Chandogulakula',
  'Chandrakula',
  'Changaalakula',
  'Channakula',
  'Charakula',
  'Cheelakula',
  'Chegollakula',
  'Chennakula',
  'Chidrupakula',
  'Chidurupella',
  'Chintaakula',
  'Chintyakula',
  'Chitraguptakula',
  'Chitrakula',
  'Daantakula',
  'Dakshakula',
  'Dashistakula',
  'Dayashistakula',
  'Dedanakula',
  'Devakula',
  'Deekshamashistakula',
  'Dentakula',
  'Denukula',
  'Deshistakula',
  'Devishetla',
  'Dhanakula',
  'Dhanagondakula',
  'Dhanapala',
  'Dhenukula',
  'Didanakula',
  'Dontakula',
  'Doorashistakula',
  'Durgakula',
  'Dyantakula',
  'Ekambari',
  'Ekshwakula',
  'Elishetla',
  'Enakula',
  'Enapakula',
  'Enasista',
  'Ganamukhakula',
  'Ganapakula',
  'Gajananakula',
  'Gandhishila',
  'Garudakula',
  'Ghanashreelakula',
  'Ghantakula',
  'Girikula',
  'Gondakakula',
  'Gopakula',
  'Gopalakula',
  'Gorantakula',
  'Gosheelakula',
  'Gouthamasa',
  'Grandhisheelakula',
  'Gundakula',
  'Guntakula',
  'Harishishnakula',
  'Hastakula',
  'Helamanchikula',
  'Hiranyakula',
  'Hiraraatakula',
  'Ikshwakula',
  'Ilamanchikula',
  'Inakala',
  'Inapakula',
  'Inchupakula',
  'Indrakula',
  'Inukula',
  'Inupakula',
  'Ishanakula',
  'Jabreyasa',
  'Jamadagnikula',
  'Janakula',
  'Kaamakula',
  'Kaalakula',
  'Kaanukula',
  'Kaarnakula',
  'Kaatakula',
  'Kamadhenukula',
  'Kamalakula',
  'Kamatakula',
  'Kanakapala',
  'Kapilakula',
  'Kartikakula',
  'Kanyakula',
  'Kapatakula',
  'Karatakula',
  'Karmakula',
  'Karnatakula',
  'Kasyapa',
  'Komirashista',
  'Korantana',
  'Kotakula',
  'Koundinyakula',
  'Koutakula',
  'Kramashistakula',
  'Kranukula',
  'Krishnashila',
  'Kumarasista',
  'Maanasakula',
  'Maarakula',
  'Maashaantakula',
  'Madanakula',
  'Maddikula',
  'Madyakula',
  'Maitreyasa',
  'Mandakula',
  'Manyukula',
  'Marichikula',
  'Markandeya',
  'Midhunakula',
  'Mitrakula',
  'Modukula',
  'Moolakula',
  'Morakula',
  'Moudgalyasa',
  'Mounjakula',
  'Mrangakula',
  'Muddukula',
  'Mulakula',
  'Munikula',
  'Munukula',
  'Naabhillakula',
  'Nandigosheelakula',
  'Nandishila',
  'Narayanakula',
  'Nrisimhakula',
  'Paanchalakula',
  'Padagashila',
  'Padmakula',
  'Padmashistakula',
  'Pagidikula',
  'Paidikula',
  'Palakakula',
  'Pallavagosheelakula',
  'Pambalakula',
  'Parasrasa',
  'Parasharakula',
  'Patanakula',
  'Paulastyakula',
  'Pavulasthyasa',
  'Peddashista',
  'Pellikula',
  'Pendlikula',
  'Perushistakula',
  'Pingalasa',
  'Pippaalakula',
  'Pouchakula',
  'Poulashya',
  'Poutsakula',
  'Praanakula',
  'Pragbalakula',
  'Prahanakula',
  'Praudasheelakula',
  'Pravalakula',
  'Prolakula',
  'Proshistakula',
  'Proudayaajakula',
  'Pruthivishrestakula',
  'Puchhakula',
  'Pumshimaamshikula',
  'Punagashila',
  'Puneetakula',
  'Punyashila',
  'Puppala',
  'Puppaalakula',
  'Pushpala',
  'Pydikula',
  'Ravishistakula',
  'Rentakula',
  'Rudrakula',
  'Saanakula',
  'Saantaalakula',
  'Samashistakula',
  'Sanakula',
  'Sanatkula',
  'Sanikula',
  'Sannakula',
  'Satyagoshila',
  'Shaanakula',
  'Shaantikula',
  'Shamanakula',
  'Shankarakula',
  'Shrivatsakula',
  'Shirisheshtakula',
  'Shreegoshila',
  'Shreshtamandakula',
  'Sirisetla',
  'Snigdakula',
  'Sreedharasa',
  'Sreelakula',
  'Sreerangakula',
  'Sreevatsasa',
  'Srivatsasa',
  'Strilakula',
  'Sukaalakula',
  'Sundarasa',
  'Surakula',
  'Surashistakula',
  'Suryakula',
  'Susillakula',
  'Thankaalakula',
  'Thotakula',
  'Thrivikramasistakula',
  'Tolakula',
  'Tontikula',
  'Trimoolakula',
  'Trivikramashista',
  'Trukashistakula',
  'Tulamanchikula',
  'Tulashistakula',
  'Tulasikula',
  'Tuppaalakula',
  'Turyatakula',
  'Udvahakula',
  'Ugrasenasa',
  'Upamakula',
  'Upamanyukula',
  'Upanakula',
  'Urishista',
  'Ushirakula',
  'Utakula',
  'Uttamagosheelakula',
  'Uttamakula',
  'Uttamasheelakula',
  'Vakkaakula',
  'Vanashistakula',
  'Varunakula',
  'Vasantakula',
  'Vasishthakula',
  'Vashistasa',
  'Vastrakula',
  'Velashistakula',
  'Venashista',
  'Venkaakula',
  'Vennakula',
  'Vikramashistakula',
  'Vimarashetla',
  'Vinnakula',
  'Vinukula',
  'Viparishetla',
  'Vishnukula',
  'Vishpalakula',
  'Vishwaksenasa',
  'Vridhikula',
  'Vyalakula',
  'Yaanasakula',
  'Yaskasa',
  'Yelamanchikula',
  'Yelashistakula',
  'Yelishetla',
  'Yennakula',
  'Yerasistakula'
];
