// Raasi options (zodiac order: Aries to Pisces)
export const raasiOptions = [
  'Mesha (Aries) – మేషం ♈',
  'Vrishabha (Taurus) – వృషభం ♉',
  'Mithuna (Gemini) – మిథునం ♊',
  'Karka (Cancer) – కర్కాటకం ♋',
  'Simha (Leo) – సింహం ♌',
  'Kanya (Virgo) – కన్య ♍',
  'Tula (Libra) – తుల ♎',
  'Vrischika (Scorpio) – వృశ్చికం ♏',
  'Dhanu (Sagittarius) – ధనుస్సు ♐',
  'Makara (Capricorn) – మకరం ♑',
  'Kumbha (Aquarius) – కుంభం ♒',
  'Meena (Pisces) – మీనం ♓'
];

// Star options (Nakshatra order)
export const starOptions = [
  'Ashwini – అశ్విని',
  'Bharani – భరణి',
  'Krittika – కృత్తిక',
  'Rohini – రోహిణి',
  'Mrigashira – మృగశిర',
  'Ardra – ఆర్ద్ర',
  'Punarvasu – పునర్వసు',
  'Pushya – పుష్య',
  'Ashlesha – ఆశ్లేష',
  'Magha – మఘ',
  'Purva Phalguni – పూర్వ ఫల్గుణి',
  'Uttara Phalguni – ఉత్తర ఫల్గుణి',
  'Hasta – హస్త',
  'Chitra – చిత్ర',
  'Swati – స్వాతి',
  'Vishakha – విశాఖ',
  'Anuradha – అనురాధ',
  'Jyeshtha – జ్యేష్ఠ',
  'Moola – మూల',
  'Purva Ashadha – పూర్వాషాఢ',
  'Uttara Ashadha – ఉత్తరాషాఢ',
  'Shravana – శ్రవణ',
  'Dhanishta – ధనిష్ఠ',
  'Shatabhisha – శతభిష',
  'Purva Bhadrapada – పూర్వ భాద్రపద',
  'Uttara Bhadrapada – ఉత్తర భాద్రపద',
  'Revati – రేవతి'
];

export const padamOptions = [
  '1st Padam',
  '2nd Padam',
  '3rd Padam',
  '4th Padam'
];

export const gothramOptions = [
  'Aarakyamula (ఆరక్యముల)',
  'Akramulakula (అక్రములకుల)',
  'Akyamulakula (అక్యములకుల)',
  'Amalakula (అమలకుల)',
  'Ananthakula (అనంతకుల)',
  'Anubala (అనుబాల)',
  'Anubala Gula (అనుబాల గుల)',
  'Anubha Gula (అనుభ గుల)',
  'Arisetlakula (అరిశెట్లకుల)',
  'Arisistakula (అరిశిష్టకుల)',
  'Arasakula (అరసకుల)',
  'Dhanakula (ధనకుల)',
  'Elisistakula (ఎలిశిష్టకుల)',
  'Gandhiseela (గంథిశీల)',
  'Gandhiseelakula (గంథశీలకుల)',
  'Ganamukukula (గనముకు కుల)',
  'Garnakula (గర్నకుల)',
  'Grandhiseela (గ్రంథిశీల)',
  'Harisistakula (హరిశిష్టకుల)',
  'Hasthakula (హస్తకుల)',
  'Ikshvakukula (ఇక్ష్వాకుకుల)',
  'Kamasista (కమశిష్ట)',
  'Kanalola (కనలోల)',
  'Kanasrila (కనశ్రిల)',
  'Kanasrilakula (కనశ్రిలకుల)',
  'Kanukula (కనుకుల)',
  'Kanyakula (కన్యాకుల)',
  'Karakapala (కరకపల)',
  'Komarsistakula (కొమర్శిష్టాకుల)',
  'Kranu (క్రను)',
  'Kranukula (క్రనుకుల)',
  'Kumarisista (కుమిరిశిష్ట)',
  'Kumarsista (కుమర్శిష్ట)',
  'Mandakula (మందకుల)',
  'Mandhakula (మంధకుల)',
  'Mandu (మండు)',
  'Paipikula (పైపికుల)',
  'Praheenikula (ప్రహీనికుల)',
  'Praheenukula (ప్రహీనుకుల)',
  'Samanakula (సమనకుల)',
  'Sarakula (శరకుల)',
  'Segolla (శెగొల్ల)',
  'Sekotlakula (శెకొట్లకుల)',
  'Sreshta Kundalakula (శ్రేష్ఠ కుండలకుల)',
  'Thanankula (థననకుల)',
  'Thenukula (థెనుకుల)',
  'Uthakalakula (ఉథకలాకుల)',
  'Uthakula (ఉథకుల)',
  'Uthamakula (ఉహ్థమకుల)',
  'Uthasistakula (ఉథశిష్టకుల)',
  'Venkalakula (వెంకలాకుల)',
  'Yanasabikula (యానశబికుల)',
  'Yanasakalulu (యానశకలుల)',
  'Yanasakula (యనశకుల)'
].sort();
